# playcation table
spring.datasource.data.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.data.jdbc-url=jdbc:mysql://${DB_URL}:3306/playcation
spring.datasource.data.jdbc-url=${DB_URL_1}
spring.datasource.data.username=${DB_USERNAME}
spring.datasource.data.password=${DB_PASSWORD}

# batch meta table
spring.datasource.meta.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.meta.jdbc-url=jdbc:mysql://${DB_URL}:3306/meta
spring.datasource.meta.jdbc-url=${DB_URL_2}
spring.datasource.meta.username=${DB_USERNAME}
spring.datasource.meta.password=${DB_PASSWORD}