name: GitHub Actions Demo

on:
  push:
    branches:
      - '**'  # 모든 브랜치에서 실행
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # 레포지토리 코드 가져오기

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'  # OpenJDK 배포판 사용
          java-version: '17'  # JDK 17 설정

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew  # Gradle 실행 권한 부여

      - name: Run Tests
        run: ./gradlew test  # Spring Boot 테스트 실행

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        if: always()  # 테스트가 실패해도 로그 업로드
        with:
          name: test-results
          path: build/reports/tests/test  # 테스트 리포트 경로